auth0:
  audience: https://graphql.aw-central.com
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://neonkingkong.au.auth0.com/
  data:
    mongodb:
      port: 27017
      host: localhost
      database: awc-dev
