auth0:
  audience: https://graphql.aw-central.com
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://neonkingkong.au.auth0.com/
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@awcentral-cluster-1.nnjlp.mongodb.net/cypress-awcentral?retryWrites=true&w=majority

#logging:
#  level:
#    org:
#      springframework:
#        data:
#          mongodb:
#            core:
#              MongoTemplate: DEBUG